FROM quay.io/fenicsproject/stable:latest
RUN python3 -m pip install git+https://github.com/optipulsproject/optipuls
RUN python3 -m pip install --upgrade matplotlib
WORKDIR /home/fenics/shared
CMD ["/bin/bash"]
ENTRYPOINT []
