FROM quay.io/fenicsproject/stable:latest
COPY . /home/fenics/src/python-optipuls
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install importlib_resources
RUN python3 -m pip install /home/fenics/src/python-optipuls
RUN python3 -m pip install --upgrade matplotlib
WORKDIR /home/fenics/shared
CMD ["/bin/bash"]
ENTRYPOINT []
